name: Build Geode Mod

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Win64

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: FramePerfectDetector
          path: ${{ steps.build.outputs.build-output }}/*.geode
